name: simple_live_core
version: 1.0.2
description: "聚合直播核心库"
repository: https://github.com/xiaoyaocz/simple_live_client
publish_to: "none"
environment: 
  sdk: '>=2.19.1 <3.0.0'

dependencies: 
  dio: ^5.3.2
  logger: ^2.0.2
  web_socket_channel: ^2.4.0
  html_unescape: ^2.0.0
  protobuf: ^3.1.0
  crypto: ^3.0.3
  brotli: ^0.6.0
  dart_tars_protocol:
    git: https://github.com/xiaoyaocz/dart_tars_protocol.git

dev_dependencies: 
  lints: ^2.0.0
  test: ^1.21.0

